import sympy as sp

print("="*72)
print("ETAPE 1 : LE DICTIONNAIRE LINEAIRE EXACT  PU(w1,w2)  <->  dimere PT(kappa,gamma)")
print("="*72)
w1,w2 = sp.symbols('omega1 omega2', positive=True)
q1,q2,p1,p2 = sp.symbols('q1 q2 p1 p2', real=True)

# Hamiltonien d'Ostrogradsky du PU libre (celui de pu_test.py)
H = p1*q2 + sp.Rational(1,2)*p2**2 + sp.Rational(1,2)*(w1**2+w2**2)*q2**2 - sp.Rational(1,2)*w1**2*w2**2*q1**2

# Modes normaux : (d^2+w2^2)x isole l'oscillation w1, et vice versa.
# En variables d'Ostrogradsky : x=q1, x'=q2, x''=p2, x'''=-p1-(w1^2+w2^2)q2
X1 = (p2 + w2**2*q1)/(w2**2-w1**2);  V1 = (-p1 - w1**2*q2)/(w2**2-w1**2)   # V1 = dX1/dt
X2 = (p2 + w1**2*q1)/(w1**2-w2**2);  V2 = (-p1 - w2**2*q2)/(w1**2-w2**2)
# Verification : H doit devenir  c1*(V1^2+w1^2 X1^2) - c2*(V2^2+w2^2 X2^2)
c1,c2 = sp.symbols('c1 c2')
target = c1*(V1**2+w1**2*X1**2) + c2*(V2**2+w2**2*X2**2)
sol = sp.solve(sp.Poly(sp.expand(H - target),(q1,q2,p1,p2)).coeffs(),[c1,c2])
print(f"  H_PU = c1*(V1^2+w1^2*X1^2) + c2*(V2^2+w2^2*X2^2)  avec :")
print(f"    c1 = {sp.simplify(sol[c1])}    c2 = {sp.simplify(sol[c2])}")
print(f"  => pour w1>w2 :  c1>0, c2<0.  H = (w1^2-w2^2)/2 * [ E_+(w1)  -  E_-(w2) ]")
print(f"     Le PU libre EST deux oscillateurs POSITIFS avec un MOINS relatif. Etabli.")
print(f"  !! La transformation ~ 1/(w1^2-w2^2) : SINGULIERE au point de Jordan w1=w2. !!")
print()

# Cote dimere : i a' = i g a + k b ; i b' = -i g b + k a  ->  frequences +/- Omega
k,g = sp.symbols('kappa gamma', positive=True)
M = sp.Matrix([[sp.I*g, k],[k, -sp.I*g]])
evs = list(M.eigenvals().keys())
print(f"  Dimere PT lineaire : valeurs propres = {evs}  ->  +/- Omega, Omega=sqrt(kappa^2-gamma^2)")
print(f"  Avec une phase globale (jauge optique) beta, les frequences deviennent beta +/- Omega.")
print(f"  IDENTIFICATION :  omega1 = beta + Omega  (mode +, energie POSITIVE)")
print(f"                    omega2 = Omega - beta  (mode -, frequence NEGATIVE = energie NEGATIVE)")
print(f"  =>  Omega = (omega1+omega2)/2,   beta = (omega1-omega2)/2.")
print()
print("  >>> DICTIONNAIRE LINEAIRE : EXACT. Et avec un cadeau : <<<")
print("  kappa^2 - gamma^2 = Omega^2 fixe seulement la DIFFERENCE. Le taux de gain/perte")
print("  gamma est LIBRE : c'est une JAUGE (l'orbite de la carte de Dyson). Au niveau")
print("  lineaire, 'indefini conservatif' et 'gain/perte' sont le MEME systeme, a jauge pres.")
print()

print("="*72)
print("ETAPE 2 : POUSSER L'INTERACTION A TRAVERS -- la moyenne resonante (RWA)")
print("="*72)
# x = cA(A z1 + Ac/z1) + cB(B/z2 + Bc z2), z1=e^{-i w1 t}, z2=e^{-i w2 t} ; B a freq +w2
cA,cB = sp.symbols('c_A c_B', positive=True)
A,Ac,B,Bc,z1,z2 = sp.symbols('A Abar B Bbar z1 z2')
x = cA*(A*z1 + Ac/z1) + cB*(B/z2 + Bc*z2)
gq = sp.symbols('g_4', positive=True)
V = sp.expand(gq*x**4/4)
# RWA : pour w1/w2 generique (ex. sqrt(2)), ne garder que les termes SANS z1 ni z2
Vp = sp.Poly(sp.expand(V*z1**4*z2**4),(z1,z2))
VRWA = sum(coef for mono,coef in zip(Vp.monoms(),Vp.coeffs()) if mono==(4,4))
VRWA = sp.simplify(VRWA)
print(f"  V_RWA = {VRWA}")
NA,NB = sp.symbols('N_A N_B', positive=True)
VN = VRWA.subs({A*Ac:NA, B*Bc:NB}); VN = sp.expand(VN.subs({Ac:0,A:0,B:0,Bc:0}) + VN) # crude
VN = sp.simplify(VRWA.subs({Ac: NA/A, Bc: NB/B}))
print(f"        = {sp.expand(VN)}   [avec N_A=|A|^2, N_B=|B|^2]")
print()
print("  >>> V_RWA ne depend QUE des ACTIONS N_A, N_B (pour w1/w2 generique -- pas de")
print("      resonance 1:1, 1:3, 3:1). Donc {N_A,H_RWA}={N_B,H_RWA}=0 : les actions GELENT.")
print("      THEOREME (ordre resonant dominant) : le fantome PU en interaction est BENIN.")
print("      La malignite N'EST PAS dans le terme dominant : elle vient des RESONANCES")
print("      d'ordre superieur (les frequences glissent avec l'amplitude : dw_A ~ +g N_A,")
print("      dw_B ~ -g N_B -> a une certaine amplitude, un rapport rationnel bas est atteint,")
print("      recouvrement de Chirikov, chaos -- et l'INDEFINITUDE convertit ce chaos borne")
print("      en fuite : H = w1 N_A - w2 N_B = const autorise N_A, N_B -> infini ENSEMBLE.")
print()
print("="*72)
print("ETAPE 3 : LE VERDICT STRUCTUREL -- ou le dictionnaire casse")
print("="*72)
print("  Cote PU (conservatif indefini) : N_A, N_B proteges au premier ordre ; la fuite")
print("     passe par le canal des RESONANCES (lent, structure en langues, KAM).")
print("  Cote dimere (gain/perte) : gamma pompe N directement : dN/dt = 2 gamma(|a|^2-|b|^2).")
print("     La fuite passe par le canal de la NORME (rapide, seuil lisse). AUCUNE resonance requise.")
print("  => L'interaction BRISE la jauge gamma : les deux systemes, identiques au niveau")
print("     lineaire, paient le moins par DEUX CANAUX DIFFERENTS. Le dictionnaire nonlineaire")
print("     n'est pas faux -- il est REVELATEUR : il factorise la malignite en deux mecanismes.")
